### ISSUE TITLE
Oplevering Moodle 4.2 + PHP 8.0

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist#2]
Graag informeren wij jullie over de oplevering van de Moodle plug-in(s) en eventuele aanpassingen die jullie hebben aangevraagd. Zouden jullie de functionaliteit ervan kunnen controleren en nagaan of alles naar verwachting werkt? Eventuele vragen of opmerkingen vernemen wij graag.

Bijgevoegd vinden jullie de links naar de repositories:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist/tree/86bwwnb0j-MOODLE42

Na jullie testen zien we graag jullie akkoord tegemoet voor het doorvoeren van de wijzigingen naar de main/master branch.

**Comment by gemguardian** [comment]
@luukverhoeven ik heb dit getest op M4.2 en 4.3. 

Zou jij 

A) de huidge master > 4.1 kunnen maken
B) van deze M4.2 kunnen maken 
C) dan de master zelf op versie 4.3 kunnen zetten - Uiteraard inclusief de juiste version .php verwijzing. 

En dan zorgen dat op Moodle.org / plugin de 4.2 én 4.3 beschikbaar komt? 

Dank!

**Comment by luukverhoeven** [comment]
@gemguardian Git is bijgewerkt. De plug-in kan ik niet bijwerken op moodle.org, kun je me toevoegen?

**Comment by gemguardian** [comment]
@luukverhoeven ik kan de optie zo niet vinden. Ik heb 4.2 zelf toegevoegd, maar de Master moet ik denk ik nog aanpassen voor 4.3 of niet?

**Comment by luukverhoeven** [comment]
@gemguardian 

De plug-in is door ons getest en bijgewerkt tot versie 4.2.

Het testen en eventueel bijwerken van versie 4.3 voor deze plug-in moet nog worden gepland. Er staat een taak op onze lijst waarin wordt gevraagd of wij de plug-ins hebben bijgewerkt. Hierop kom ik z.s.m. terug
