### ISSUE TITLE
Moodle 4.3 -release

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist#3]
@gemguardian Successfully tested on Moodle 4.3 with no issues detected. 
Changes have been applied to the Changelog and version number.
https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist/tree/86by49r4k-MOODLE43

**Comment by gemguardian** [comment]
@luukverhoeven akkoord zorg je dat het in een aparte branche komt en doorgaat naar  Moodle.org? 
de 4.4 versie test ik deze week.

**Comment by luukverhoeven** [comment]
Kan nog niet doorzetten naar Moodle.org, zie #4

**Comment by gemguardian** [comment]
Zie https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist/issues/4 - ik heb je toegang gegeven

**Comment by luukverhoeven** [comment]
@gemguardian Doorgezet: https://moodle.org/plugins/block_quickcourselist/versions
