### ISSUE TITLE
Moodle 4.4 - release

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist#4]
Hi @gemguardian, 

Hereby the Moodle 4.4 release. No real changes needed, still works with M4.4. 
https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist/tree/86bwwnckq-MOODLE44

**Comment by gemguardian** [comment]
@luukverhoeven dit is akkoord

**Comment by luukverhoeven** [comment]
@gemguardian Kun je mij toevoegen aan https://moodle.org/plugins/block_quickcourselist 

Aan de onderkant van de pagina kan dat via:
![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist/assets/995760/f8558df7-490f-452d-866b-51a9daae2613)


1487326
https://moodle.org/user/profile.php?id=1487326

--
Zie overigens een error op Moodle.org op je profile pagina:
![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist/assets/995760/ceb1e2ea-2b6a-4734-927d-3e6a80b26fa3)

**Comment by gemguardian** [comment]
Ik heb de fout melding gezien maar er is niets in mij profiel dat er op wijst - en geen zin om te meldde. 
Ik heb je toegevoegd

**Comment by luukverhoeven** [comment]
@gemguardian Doorgezet: https://moodle.org/plugins/block_quickcourselist/versions
