### ISSUE TITLE
Moodle 4.5 release

### ISSUE THREAD

**Issue by luukverhoeven** [Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist#7]
Hi @gemguardian @servicedeskltnc ,

We would like to inform you about the delivery of the Moodle plugin and any adjustments you have requested. 
Please check their functionality and verify if everything is working as expected. We would appreciate hearing any questions or comments you might have.

Attached you will find the links to the repositories:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-block_quickcourselist/tree/86by49jwt-upgrade-moodle45

After your testing, we look forward to receiving your approval to proceed with applying the changes to the main/master branch.

**Comment by emmarichardson** [comment]
Thank you - this works well and overcomes the big space issue that the previous version was using.  Can you tell me exactly what you did to fix that - I also have the quickfindlist on my site and it is having the same issue...

**Comment by emmarichardson** [comment]
Ignore previous comment - must have been something with my site.

**Comment by gemguardian** [comment]
@luukverhoeven could you please push it to main and release it on Moodle.org

**Comment by luukverhoeven** [comment]
@gemguardian This is now released
